version: \"$DOCKER_YML_VERSION\"
services:

  # ELK framework Ship Platform
  ${lsite}elasticsearch:
    image: happyface/elasticsearch
    volumes:
      - \"$PWD/$PAYLOADS_DIR/ssh:/root/.ssh\"
      - \"$PWD/$PAYLOADS_DIR/data/${site}/billing:/billing\"
      - \"$PWD/$PAYLOADS_DIR/sites/${site}/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml\"
      - \"$PWD/$PAYLOADS_DIR/data/${site}/elasticsearch_index_data:/usr/share/elasticsearch/data\"
    ports:
      - \"9200:9200\"
      - \"9300:9300\"
    environment:
      #ES_JAVA_OPTS: \"-Xmx5g -Xms5g -XX:NewSize=16g -XX:MaxNewSize=16g -XX:MaxTenuringThreshold=2 -XX:SurvivorRatio=30\"
      ES_JAVA_OPTS: \"-Xmx7g -Xms7g\"
    networks:
      - elk

  ${lsite}logstash_billing:
    image: happyface/logstash
    volumes:
      - \"$PWD/$PAYLOADS_DIR/ssh:/root/.ssh\"
      - \"$PWD/$PAYLOADS_DIR/data/${site}/billing:/billing\"
      - \"$PWD/$PAYLOADS_DIR/sites/${site}/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml\"
      - \"$PWD/$PAYLOADS_DIR/sites/${site}/logstash/pipeline:/usr/share/logstash/pipeline\"
      - \"$PWD/$PAYLOADS_DIR/sites/${site}/logstash/patterns:/usr/share/logstash/patterns\"
    ports:
      - \"5000:5000\"
    environment:
      LS_JAVA_OPTS: \"-Xmx1g -Xms1g\"
    networks:
      - elk
    depends_on:
      - ${lsite}elasticsearch

  ${lsite}logstash_htcondor:
    image: happyface/logstash
    volumes:
      - \"$PWD/$PAYLOADS_DIR/ssh:/root/.ssh\"
      - \"$PWD/$PAYLOADS_DIR/data/${site}/htcondor:/htcondor\"
      - \"$PWD/$PAYLOADS_DIR/sites/${site}/logstash_htcondor/logstash.yml:/usr/share/logstash/config/logstash.yml\"
      - \"$PWD/$PAYLOADS_DIR/sites/${site}/logstash_htcondor/pipeline:/usr/share/logstash/pipeline\"
      - \"$PWD/$PAYLOADS_DIR/sites/${site}/logstash_htcondor/patterns:/usr/share/logstash/patterns\"
    ports:
      - \"5100:5000\"
    environment:
      LS_JAVA_OPTS: \"-Xmx1g -Xms1g\"
    networks:
      - elk
    depends_on:
      - ${lsite}elasticsearch


  ${site}:
    image: happyface/kibana
    ports:
      - \"20261:5601\"
      - \"${ssh_port}:$DEFAULT_SSH_PORT\"
    networks:
      - elk
    depends_on:
      - ${lsite}elasticsearch

    volumes:
      - \"$PWD/$PAYLOADS_DIR/ssh:/root/.ssh\"
      - \"$PWD/$PAYLOADS_DIR/data/${site}/billing:/billing\"
      - \"$PWD/$PAYLOADS_DIR/sites/${site}/kibana/:/usr/share/kibana/config\"
    # The followings are to avoid D-Bus error in CentOS7
      - \"/sys/fs/cgroup:/sys/fs/cgroup:ro\"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

networks:

  elk:
    driver: bridge
