version: "2.0"

services:
 # HappyFace & Mobile Application Device Integration platform

 ## Services prividing HF & HF Mobile on CentOS6
 hmf.el7:
  build: hmf.el7
  image: happyface/hmf.el7

 ## Services prividing HF & HF Mobile on CentOS6
 hmf.el6:
  build: hmf.el6
  image: happyface/hmf.el6
